Pull request
alexawesomecode/apple-clone-project pull request #2
Opened 2019-10-04 15:50 UTC by alexawesomecode

This is a pull request that applies the requirements needed for the apple-clone-project.

2019-10-04 17:36 UTC, uche-inyama requested changes
## Hi alex! nice job with the improvisation :slightly_smiling_face: 

But there are some updates we need to make.

- [ ] Your Html document did not pass a validation test, kindly use this [link](https://validator.w3.org), to check for the validation error.

- [ ] Using sematic html tags; wrap the main content of your html document in a **```<main> tag```** and use **```<nav> tag```** for the navigation section.

- [ ] Implement the hover effect on your on your navigation links.

## After implementing these changes submit another form a code review :slightly_smiling_face:

2019-10-04 17:36 UTC, uche-inyama commented on index.html
> +
The images should be wrapped in an **```<a>```** tag. The images are link to another articles or `#`

2019-10-04 20:44 UTC, samgaco requested changes
Hi Alex :high_brightness: 

Everything required has been implemented, you only have left the following point:

- [ ] **[REQUIERED]** You should fix the errors given to you by the[ validator ](https://validator.w3.org)when uploading the index file.

Please :pray: work on that and submit back for another code review once you are done.

Regards! :muscle: 

-------------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-04 20:44 UTC, samgaco commented on index.html
> +<main>
:+1:

2019-10-04 20:44 UTC, samgaco commented on style.css
> +.nav-bar li:hover {
:100:

2019-10-04 20:56 UTC, alexawesomecode commented
done! 
fixed the mispelling
thanks,

alex

2019-10-07 18:33 UTC, alexawesomecode commented
hello

i have done the checking a couple of times and it doesn't give me any error,

i am using this: https://validator.w3.org



El vie., 4 de oct. de 2019 a la(s) 17:44, samgaco (notifications@github.com)
escribió:

> *@samgaco* requested changes on this pull request.
>
> Hi Alex 🔆
>
> Everything required has been implemented, you only have left the following
> point:
>
>    - *[REQUIERED]* You should fix the errors given to you by the
>    validator <https://validator.w3.org>when uploading the index file.
>
> Please 🙏 work on that and submit back for another code review once you
> are done.
>
> Regards! 💪
> ------------------------------
>
>    - STATUS OF THE PROJECT: REQUESTED CHANGES 🛑
>
> ------------------------------
>
> In index.html
> <https://github.com/alexawesomecode/apple-clone-project/pull/2#discussion_r331678446>
> :
>
> > @@ -0,0 +1,104 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +
>
> +<head>
>
> +    <meta charset="UTF-8" />
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>
> +    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
>
> +    <link rel="stylesheet" href="style.css" />
>
> +    <title>Apple</title>
>
> +</head>
>
> +
>
> +<main>
>
>
> 👍
> ------------------------------
>
> In style.css
> <https://github.com/alexawesomecode/apple-clone-project/pull/2#discussion_r331678554>
> :
>
> > +  background: linear-gradient(0deg, rgba(122, 122, 126, 0.9780287114845938) 0%, rgba(93, 93, 94, 1) 57%, rgba(132, 132, 135, 0.9640231092436975) 93%);
>
> +}
>
> +
>
> +.nav-bar ul > li {
>
> +  flex: 1;
>
> +  height: 34px;
>
> +  border-right: 2px solid gray;
>
> +  padding: 8px;
>
> +  color: white;
>
> +  font-weight: 200;
>
> +  font-family: sans-serif, Arial;
>
> +  font-size: 14px;
>
> +  cursor: pointer;
>
> +}
>
> +
>
> +.nav-bar li:hover {
>
>
> 💯
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexawesomecode/apple-clone-project/pull/2?email_source=notifications&email_token=ALOGPQIVM6I47BLFYILLJALQM6TMPA5CNFSM4I5RQBDKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCG7KU6Y#pullrequestreview-297708155>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALOGPQLVHY5JDDVVTXWP57DQM6TMPANCNFSM4I5RQBDA>
> .
>

2019-10-08 17:06 UTC, uche-inyama approved these changes
## Hi alex! 

Everything looks good now.

Go ahead and merge with the master branch :slightly_smiling_face: 

#### ```Have a great day``` :slightly_smiling_face:

2019-10-08 19:26 UTC, merged